export const DEFAULTPROPERTIES = {
  RequiredStarPosition: "right-2 top-1",
  RequiredStarColor: "text-red-500",
  RequiredStarFontSize: "text-lg",
  BackgroundColor: "bg-gray-100",
  BackgroundColorOnError: "bg-red-400",
  BorderColor: "border-gray-600",
  BorderColorOnFocus: "border-gray-200",
  BorderColorOnHover: "hover:border-gray-400",
  BorderColorOnError: "border-red-600",
  BorderRadius: "rounded-md",
  BackgroundOpacity: "bg-opacity-5",
  BackgroundOpacityOnError: "bg-opacity-30",
  TextColor: "text-white",
  TextSize: "text-md",
  LabelColor: "text-slate-400",
  LabelColorOnFocus: "text-slate-300",
  LabelColorOnError: "text-red-600",
  LabelFontSize: "text-md",
  IconColor: "text-gray-400",
  IconColorOnFocus: "hover:text-gray-300",
  IconFontSize: "text-xl",
  ErrorMessageColor: "text-red-600",
  ErrorMessageFontSize: "text-xs",
  ErrorMessagePosition: "left-0 top-full",
  TransitionDuration: "duration-300",
};

export default DEFAULTPROPERTIES;
